version: '3'

services:
  ssh:
    container_name: ssh
    restart: always
    image: fuzhiwen/market-ssh:1.0.2
    ports:
      - "10022:22"
    volumes:
      - /home/boya_market:/home/boya_market

  swagger-ui:
    container_name: swagger-ui
    restart: always
    image: swaggerapi/swagger-ui:latest
    ports:
      - "18080:8080"
    environment:
      - BASE_URL=/swagger

  swagger-editor:
    container_name: swagger-editor
    restart: always
    image: swaggerapi/swagger-editor:latest
    ports:
      - "18080:8080"
    environment:
      - BASE_URL=/swagger
