#
# modified from following src:
# https://gist.github.com/lvaylet/cdef4c78d2e61634d80238acd5f321be#file-atlassian-jira-docker-compose-yml
#
version: '3'

services:
  jira:
    depends_on:
      - mysql
    container_name: jira
    restart: always
    build: ./jira-software
    image: jira/jira-software:8.1.0
    environment:
      - CATALINA_OPTS=-Xms768m -Xmx1024m
      - X_PROXY_NAME=dev.iqubic.net
      - X_PROXY_PORT=18080
      - X_PROXY_SCHEME=http
      - X_PATH=/jira
    volumes:
      - jira-data:/var/atlassian/jira  # JIRA_HOME

  mysql:
    container_name: jira_mysql  # https://store.docker.com/images/mysql
    restart: always
    build: ./mysql
    image: jira/mysql:5.7
    environment:
      # Use a .env file to store credentials securely?
      # https://docs.docker.com/compose/environment-variables/
      - MYSQL_ROOT_PASSWORD=hnkNr3sThMVzcrsugqTq4VCbzM7awwRL
      - MYSQL_DATABASE=jiradb          # this database will be created on image startup
      - MYSQL_USER=jira                # this user will be granted superuser permissions on MYSQL_DATABASE
      - MYSQL_PASSWORD=MYxKYsfidur4HJNyd7zzNkqEFcUNtyMH
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    depends_on:
      - jira
    container_name: jira_nginx
    restart: always
    image: nginx:1.15-alpine
    ports:
      - "18080:80"
    environment:
      - X_PROXY_NAME=dev.iqubic.net
      - X_PROXY_PORT=18080
      - X_PROXY_SCHEME=http
      - X_PATH=/jira
    command: >
      /bin/sh -c
      "envsubst '
      $$X_PROXY_NAME
      $$X_PROXY_PORT
      $$X_PROXY_SCHEME
      $$X_PATH
      ' </etc/nginx/conf.d/jira_site.template > /etc/nginx/conf.d/default.conf
      && cat /etc/nginx/conf.d/default.conf
      && exec nginx -g 'daemon off;'"
    volumes:
      - ./nginx/jira_site.template:/etc/nginx/conf.d/jira_site.template


volumes:
  jira-data:
  mysql-data:
