#
# modified from following src:
# https://gist.github.com/lvaylet/cdef4c78d2e61634d80238acd5f321be#file-atlassian-jira-docker-compose-yml
#
version: '3'

services:
  dev:
    # 开发环境 -- 虚拟服务
    container_name: dev
    hostname: dev
    restart: "no"
    build:
      context: ./dev
      dockerfile: Dockerfile
      args:
        - PASSWORD_root=${PASSWORD_root}
        - SSH_KEY_root=${SSH_KEY_root}
        - GID_boya=${GID_boya}
        - GID_boya_market=${GID_boya_market}
        - GID_boya_sip=${GID_boya_sip}
        - UID_boya_market=${UID_boya_market}
        - UID_boya_sip=${UID_boya_sip}
        - PASSWORD_boya_market=${PASSWORD_boya_market}
        - PASSWORD_boya_sip=${PASSWORD_boya_sip}
    image: "${DOCKER_REPO_PREFIX}dev:${IMG_TAG_dev}"

  sip:
    # SIP开发环境 -- 虚拟服务
    container_name: sip
    hostname: sip
    restart: "no"
    build:
      context: ./sip
      dockerfile: Dockerfile
      args:
        - DOCKER_REPO_PREFIX=${DOCKER_REPO_PREFIX}
        - IMG_TAG_ssh=${IMG_TAG_ssh}
    image: "${DOCKER_REPO_PREFIX}sip:${IMG_TAG_sip}"

  ssh:
    # 开发节点、跳转机
    container_name: ssh
    hostname: ssh
    restart: "always"
    build:
      context: ./ssh
      dockerfile: Dockerfile
      args:
        - DOCKER_REPO_PREFIX=${DOCKER_REPO_PREFIX}
        - IMG_TAG_dev=${IMG_TAG_dev}
    image: "${DOCKER_REPO_PREFIX}ssh:${IMG_TAG_ssh}"
    ports:
      # ssh
      - "${SSH_PUBLISH_PORT_SSH:-10022}:22"
      # mosh-server
      - "60100:60150/udp"
      # vnc-server
      - "15901-15910:5901-5910"
    networks:
      public:
        ipv4_address: ${NETWORK_PUBLIC_PREFIX}.${IPADDR_SUFFIX_SSH:-11}
      srvdoom1:
        ipv4_address: ${NETWORK_SRVDOOM1_PREFIX}.${IPADDR_SUFFIX_SSH:-11}
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"

  device-ui:
    # web portal
    container_name: device-ui
    hostname: device-ui
    depends_on:
      - device-gw
    restart: "always"
    image: "${DOCKER_REPO_PREFIX}ssh:${IMG_TAG_ssh}"
    ports:
      # ssh
      #- "10023:22"
      # web portal port
      - "9021:9021"
    networks:
      public:
        ipv4_address: ${NETWORK_PUBLIC_PREFIX}.${IPADDR_SUFFIX_DEVICE_UI:-21}
      srvdoom1:
        ipv4_address: ${NETWORK_SRVDOOM1_PREFIX}.${IPADDR_SUFFIX_DEVICE_UI:-21}
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"

  device-gw:
    # web portal
    container_name: device-gw
    hostname: device-gw
    restart: "always"
    image: "${DOCKER_REPO_PREFIX}ssh:${IMG_TAG_ssh}"
    ports:
      # ssh
      #- "10025:22"
      # web portal port
      - "9023:9023"
    networks:
      #public:
        #ipv4_address: ${NETWORK_PUBLIC_PREFIX}.${IPADDR_SUFFIX_DEVICE_GW:-22}
      srvdoom1:
        ipv4_address: ${NETWORK_SRVDOOM1_PREFIX}.${IPADDR_SUFFIX_DEVICE_GW:-22}
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"

  market-ui:
    # web portal
    container_name: market-ui
    hostname: market-ui
    depends_on:
      - market-gw
    restart: "always"
    image: "${DOCKER_REPO_PREFIX}ssh:${IMG_TAG_ssh}"
    ports:
      # ssh
      #- "10024:22"
      # web service port
      - "9022:9022"
    networks:
      public:
        ipv4_address: ${NETWORK_PUBLIC_PREFIX}.${IPADDR_SUFFIX_MARKET_UI:-23}
      srvdoom1:
        ipv4_address: ${NETWORK_SRVDOOM1_PREFIX}.${IPADDR_SUFFIX_MARKET_UI:-23}
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"

  market-gw:
    # web portal
    container_name: market-gw
    hostname: market-gw
    restart: "always"
    image: "${DOCKER_REPO_PREFIX}ssh:${IMG_TAG_ssh}"
    ports:
      # ssh
      #- "10026:22"
      # web service port
      - "9024:9024"
    networks:
      #public:
        #ipv4_address: ${NETWORK_PUBLIC_PREFIX}.${IPADDR_SUFFIX_MARKET_GW:-24}
      srvdoom1:
        ipv4_address: ${NETWORK_SRVDOOM1_PREFIX}.${IPADDR_SUFFIX_MARKET_GW:-24}
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"

  cms0:
    # 顶层CMS
    container_name: cms0
    hostname: cms0
    restart: "always"
    image: "${DOCKER_REPO_PREFIX}sip:${IMG_TAG_sip}"
    ports:
      # ssh
      #- "10027:22"
      #
      # LiveCMS 信令服务
      #
      # sip
      - "5060:5060/tcp"
      - "5060:5060/udp"
      # http
      - "10000:10000"
      # redis (internal)
      - "26379:26379"
      #
      # LiveSMS 流媒体服务
      #
      # sip
      - "5070:5070/tcp"
      - "5070:5070/udp"
      # http
      - "10001:10001"
      # rtmp live
      - "11935:11935"
      # rtp over tcp
      #- "30000-40000:30000-40000/tcp"
      - "30000-30009:30000-30009/tcp"
      # rtp/rtcp over udp
      #- "50000-60000:50000-60000/udp"
      - "50000-50009:50000-50009/udp"
    networks:
      public:
        ipv4_address: ${NETWORK_PUBLIC_PREFIX}.${IPADDR_SUFFIX_CMS0:-31}
      srvdoom1:
        ipv4_address: ${NETWORK_SRVDOOM1_PREFIX}.${IPADDR_SUFFIX_CMS0:-31}
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"

  cms1:
    container_name: cms1
    hostname: cms1
    restart: "always"
    image: "${DOCKER_REPO_PREFIX}sip:${IMG_TAG_sip}"
    ports:
      # ssh
      #- "10028:22"
      #
      # LiveCMS 信令服务
      #
      # sip
      - "5061:5061/tcp"
      - "5061:5061/udp"
      # http
      - "10002:10002"
      # redis (internal)
      - "26380:26380"
      #
      # LiveSMS 流媒体服务
      #
      # sip
      - "5071:5071/tcp"
      - "5071:5071/udp"
      # http
      - "10003:10003"
      # rtmp live
      - "11936:11936"
      # rtp over tcp
      #- "30000-40000:30000-40000/tcp"
      - "30010-30019:30010-30019/tcp"
      # rtp/rtcp over udp
      #- "50000-60000:50000-60000/udp"
      - "50010-50019:50010-50019/udp"
    networks:
      public:
        ipv4_address: ${NETWORK_PUBLIC_PREFIX}.${IPADDR_SUFFIX_CMS1:-32}
      srvdoom1:
        ipv4_address: ${NETWORK_SRVDOOM1_PREFIX}.${IPADDR_SUFFIX_CMS1:-32}
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"

  cms2:
    container_name: cms2
    hostname: cms2
    restart: "always"
    image: "${DOCKER_REPO_PREFIX}sip:${IMG_TAG_sip}"
    ports:
      # ssh
      #- "10029:22"
      #
      # LiveCMS 信令服务
      #
      # sip
      - "5062:5062/tcp"
      - "5062:5062/udp"
      # http
      - "10004:10004"
      # redis (internal)
      - "26381:26381"
      #
      # LiveSMS 流媒体服务
      #
      # sip
      - "5072:5072/tcp"
      - "5072:5072/udp"
      # http
      - "10005:10005"
      # rtmp live
      - "11937:11937"
      # rtp over tcp
      #- "30000-40000:30000-40000/tcp"
      - "30020-30029:30020-30029/tcp"
      # rtp/rtcp over udp
      #- "50000-60000:50000-60000/udp"
      - "50020-50029:50020-50029/udp"
    networks:
      public:
        ipv4_address: ${NETWORK_PUBLIC_PREFIX}.${IPADDR_SUFFIX_CMS2:-33}
      srvdoom1:
        ipv4_address: ${NETWORK_SRVDOOM1_PREFIX}.${IPADDR_SUFFIX_CMS2:-33}
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"

  aisrv01:
    # AI服务器
    container_name: aisrv01
    hostname: aisrv01
    restart: "always"
    image: "${DOCKER_REPO_PREFIX}ssh:${IMG_TAG_ssh}"
    #ports:
      # ssh
      #- "10030:22"
    networks:
      #public:
        #ipv4_address: ${NETWORK_PUBLIC_PREFIX}.${IPADDR_SUFFIX_AISRV01:-41}
      srvdoom1:
        ipv4_address: ${NETWORK_SRVDOOM1_PREFIX}.${IPADDR_SUFFIX_AISRV01:-41}
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"

  aisrv11:
    # AI服务器
    container_name: aisrv11
    hostname: aisrv11
    restart: "always"
    image: "${DOCKER_REPO_PREFIX}ssh:${IMG_TAG_ssh}"
    #ports:
      # ssh
      #- "10031:22"
    networks:
      #public:
        #ipv4_address: ${NETWORK_PUBLIC_PREFIX}.${IPADDR_SUFFIX_AISRV11:-42}
      srvdoom1:
        ipv4_address: ${NETWORK_SRVDOOM1_PREFIX}.${IPADDR_SUFFIX_AISRV11:-42}
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"

  aisrv21:
    # AI服务器
    container_name: aisrv21
    hostname: aisrv21
    restart: "always"
    image: "${DOCKER_REPO_PREFIX}ssh:${IMG_TAG_ssh}"
    #ports:
      # ssh
      #- "10032:22"
    networks:
      #public:
        #ipv4_address: ${NETWORK_PUBLIC_PREFIX}.${IPADDR_SUFFIX_AISRV21:-43}
      srvdoom1:
        ipv4_address: ${NETWORK_SRVDOOM1_PREFIX}.${IPADDR_SUFFIX_AISRV21:-43}
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"

  fsrouter01:
    # 特征流队列服务器
    container_name: fsrouter01
    hostname: fsrouter01
    restart: "always"
    image: "${DOCKER_REPO_PREFIX}ssh:${IMG_TAG_ssh}"
    #ports:
      # ssh
      #- "10033:22"
    networks:
      #public:
        #ipv4_address: ${NETWORK_PUBLIC_PREFIX}.${IPADDR_SUFFIX_FSROUTER01:-51}
      srvdoom1:
        ipv4_address: ${NETWORK_SRVDOOM1_PREFIX}.${IPADDR_SUFFIX_FSROUTER01:-51}
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"


volumes:
  vol-workspace:
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "${VOL_WORKSPACE_DEVICE}"

  vol-home:
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "${VOL_HOME_DEVICE}"

networks:
  default:
    #external:
    #  name: my-pre-existing-network
  public:
    ipam:
      driver: default
      config:
        - subnet: "${NETWORK_PUBLIC_PREFIX}.0/24"
  srvdoom1:
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_SRVDOOM1_MACVLAN_PARENT}
    ipam:
      driver: default
      config:
        - subnet: "${NETWORK_SRVDOOM1_PREFIX}.0/24"
