#
# modified from following src:
# https://gist.github.com/lvaylet/cdef4c78d2e61634d80238acd5f321be#file-atlassian-jira-docker-compose-yml
#
version: '3'

services:
  dev:
    container_name: dev
    hostname: dev
    restart: "no"
    build: ./dev
    image: boya/market-dev:1.0.0
    ports:
      # ssh
      - "10022:22"
      # mosh-server
      - "60100:60150/udp"
      # vnc-server
      - "15901-15910:5901-5910"
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"

  sip:
    container_name: sip
    hostname: sip2
    restart: "always"
    build: ./sip
    image: boya/market-sip:1.0.0
    ports:
      # ssh
      - "5022:22"
      #
      # LiveCMS 信令服务
      #
      # sip
      - "5060:5060/tcp"
      - "5060:5060/udp"
      # http
      - "10000:10000"
      # redis (internal)
      - "26379:26379"
      #
      # LiveSMS 流媒体服务
      #
      # sip
      - "5070:5070/tcp"
      - "5070:5070/udp"
      # http
      - "10001:10001"
      # rtmp live
      - "11935:11935"
      # rtp over tcp
      #- "30000-40000:30000-40000/tcp"
      - "30000-30100:30000-30100/tcp"
      # rtp/rtcp over udp
      #- "50000-60000:50000-60000/udp"
      - "50000-50100:50000-50100/udp"
    volumes:
      - "vol-workspace:/workspace"
      - "vol-home:/home"

volumes:
  vol-workspace:
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "/workspace"

  vol-home:
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home"
