version: '3'

services:
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
    ports:
      - '80:80'
      - '443:443'
      - '9822:22'
    volumes:
      - gitlab-cfg:/etc/gitlab:rw
      - gitlab-log:/var/log/gitlab:rw
      - gitlab-data:/var/opt/gitlab:rw
  
  redis:
    container_name: redis
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
         external_url 'https://gitlab.example.com'
        
         # Disable all services except Redis
         redis_master_role['enable'] = true
        
         # Redis configuration
         redis['port'] = 6379
         redis['bind'] = '0.0.0.0'
        
         # If you wish to use Redis authentication (recommended)
         redis['password'] = 'Redis Password'
         gitlab_rails['redis_password'] = 'Redis Password'
        
         # Disable automatic database migrations
         #   Only the primary GitLab application server should handle migrations
         gitlab_rails['auto_migrate'] = false

volumes:
  gitlab-data:
  gitlab-log:
  gitlab-cfg:
